// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8qBB5MorzA3rwbT699YqwiXRiLcKOg90',
    appId: '1:861925503724:web:5ce449a223033a5a886bc9',
    messagingSenderId: '861925503724',
    projectId: 'cz3002-ase',
    authDomain: 'cz3002-ase.firebaseapp.com',
    storageBucket: 'cz3002-ase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClx-904ij2xRpp7_7jsqyFykuHxjFTF3s',
    appId: '1:861925503724:android:0be4926768ddc2d1886bc9',
    messagingSenderId: '861925503724',
    projectId: 'cz3002-ase',
    storageBucket: 'cz3002-ase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVh8UyAqtvvNAlBHxCVxHWscwgixDpwQk',
    appId: '1:861925503724:ios:c4698c41dabf55bd886bc9',
    messagingSenderId: '861925503724',
    projectId: 'cz3002-ase',
    storageBucket: 'cz3002-ase.appspot.com',
    iosClientId: '861925503724-3roketkud3itheirnt61ihdg0tal771u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppQuitNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVh8UyAqtvvNAlBHxCVxHWscwgixDpwQk',
    appId: '1:861925503724:ios:c4698c41dabf55bd886bc9',
    messagingSenderId: '861925503724',
    projectId: 'cz3002-ase',
    storageBucket: 'cz3002-ase.appspot.com',
    iosClientId: '861925503724-3roketkud3itheirnt61ihdg0tal771u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppQuitNow',
  );
}
